import { Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { SiteHeader } from "@/components/common/SiteHeader";
import Footer from "@/components/common/Footer";
import NextTopLoader from "nextjs-toploader";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "400", "500", "600", "700", "800", "900"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const viewport = {
  themeColor: '#d90045',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  minimumScale: 1
}

export const metadata = {
  title: "North Bengal Medical College",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const topLoaderColor = "#d90045";

  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader
          color={topLoaderColor}
          initialPosition={0.08}
          crawlSpeed={200}
          height={4}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow={`0 0 10px ${topLoaderColor},0 0 5px ${topLoaderColor}`}
          zIndex={1600}
          showAtBottom={false}
        />
        <SiteHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
